name: Build SunamoOctokit

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoOctokit
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoOctokit/SunamoOctokit.csproj

    - name: Build
      run: dotnet build SunamoOctokit/SunamoOctokit.csproj --configuration Release --no-restore

  test:
    name: Test SunamoOctokit.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoOctokit.Tests/SunamoOctokit.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoOctokit.Tests/SunamoOctokit.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoOctokit.Tests/SunamoOctokit.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
